name: Rust

on:
  push:
    branches: # except for main branch.
      - "*"
      - "*/*"
      - "**"
      - "!main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: icepuma/rust-action@master
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
